# Generated by Django 5.2.3 on 2025-06-11 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancies', models.IntegerField(help_text='Number of pregnancies')),
                ('glucose', models.FloatField(help_text='Plasma glucose concentration')),
                ('blood_pressure', models.FloatField(help_text='Diastolic blood pressure (mm Hg)')),
                ('skin_thickness', models.FloatField(help_text='Triceps skin fold thickness (mm)')),
                ('insulin', models.FloatField(help_text='2-Hour serum insulin (mu U/ml)')),
                ('bmi', models.FloatField(help_text='Body mass index (weight in kg/(height in m)^2)')),
                ('diabetes_pedigree', models.FloatField(help_text='Diabetes pedigree function')),
                ('age', models.IntegerField(help_text='Age in years')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.BooleanField(help_text='Diabetes prediction (True = Diabetic, False = Non-diabetic)')),
                ('probability', models.FloatField(help_text='Probability of being diabetic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='predictor.patientdata')),
            ],
        ),
    ]
